### ISSUE TITLE
Add and register a NoopSpeedReporter

### ISSUE THREAD

**Issue by alprema** [Abc-Arbitrage/Zebus.Persistence#1]
The `IReplaySpeedReporter` interface has no default implementation and it would make it easier for the users not to have to configure it if they don't need it.

**Comment by ablanchet** [comment]
I think my last commits could close this issue : 
e14f6e77b5d861fb2e67fe7e2c1839b0b408a50d
25ddc3a2550723e8c1edb585ca9042a85433d258

We now have a [IReporter](https://github.com/Abc-Arbitrage/Zebus.Persistence/blob/master/src/Abc.Zebus.Persistence/Reporter/IReporter.cs) instead of a `ISpeedReporter` that can report more than just speed and a noop implementation.

**Comment by alprema** [comment]
Indeed, thanks.
